# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Head settings
title: ML in PL Conference 2025
email: contact@conference.mlinpl.org
event-date: "2025-10-15T00:00:00"
description: >-
  ML in PL Conference 2025 is an event focused on the best of Machine Learning both in academia and in business.
main-image: images/mlinpl-conference-2025-logo-black.png
twitter-username: "@MLinPL"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://conference.mlinpl.org" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: ML in PL Association
  url: https://mlinpl.org


# Header settings
inline-logo: '<span class="logo"><span class="main-name">ML <span class="emph">i</span>n PL</span> <span class="sub-name">Conference 2025</span></span>'
mlinpl-inline-logo: <span class="logo"><span class="main-name">ML&nbsp;<span class="emph">i</span>n&nbsp;PL</span></span>
header:
  heading: '<img src="images/mlinpl-conference-2025-logo-black.png" alt="ML in PL Conference 2025" style="max-height: 1.5em; max-width: 90%;">'
  date-location: 15 - 18 October / Copernicus Science Centre, Warsaw, Poland

  # Countdown settings
  countdown-date: "2025-10-15T08:00:00"
  # countdown-overwrite: 'Thank you for participating!</br>Find the <i class="fa-solid fa-camera-retro"></i> photos <a href="/photos">here</a>'

  # arrow-url: "#about"
  # When tickets section added, change to this
  arrow-url: "#tickets" 

  # Meetup countdown settings
  meetup-countdown-date: "2024-06-20T17:45:00"


# Navigation settings
navigation:
  - name: "/ Tickets"
    url: "#tickets"

  - name: "/ About"
    url: "#about"
    subsites:
      - name: "/ More information"
        url: "/about-ml-in-pl-conference"
      # - name: "/ Photos"
      #   url: "/photos"
      - name: "/ Previous editions"
        subsites:
          - name: "/ 2024"
            url: "https://conference2024.mlinpl.org"
          - name: "/ 2023"
            url: "https://conference2023.mlinpl.org"
          - name: "/ 2022"
            url: "https://conference2022.mlinpl.org"
          - name: "/ 2021"
            url: "https://conference2021.mlinpl.org"
          - name: "/ 2020"
            url: "https://conference2020.mlinpl.org"
          - name: "/ 2019"
            url: "https://conference2019.mlinpl.org"
          - name: "/ 2018"
            url: "https://conference2018.mlinpl.org"
          - name: "/ 2017"
            url: "https://conference2017.mlinpl.org"

  - name: "/ Program"
    url: "#program"
    subsites:
  #     # - name: "/ Agenda"
  #     #   url: "#agenda"
  #     # - name: "/ Invited speakers"
  #     #   url: "#invited-speakers"
      - name: "/ Discussion panels"
        url: "#panels"
  #     # - name: "/ Full program"
  #     #   url: "/program"
  #     # - name: "/ Conference game"
  #     #   url: "/badge-game"
      - name: "/ Call for Contributions"
        url: "/call-for-contributions"
      - name: "/ Call for Tutorials"
        url: "/call-for-tutorials"
      - name: "/ Venue"
        url: "#venue"
  #     # - name: "/ Conference booklet"
  #     #   url: "/docs/mlinpl_2024_booklet.pdf"
  #     - name: "/ Pre-conference meetups"
  #       url: "/meetups"
  #     # - name: '<span class="main-name">ML <span style="color: #4BCAFD !important;">i</span>n PL</span> <span class="sub-name">AI ART FESTIVAL</span>'
  #     #   url: https://aiart.mlinpl.org/
  #     #   target: "_blank"
  
  - name: "/ Timeline"
    url: "#timeline"

  - name: "/ Call for Sponsors"
    url: "#call-for-sponsors"

  # - name: "/ Sponsors & partners"
  #   url: "#sponsors"

  - name: "/ Organizers"
    url: "#organizers"
    subsites:
      - name: "/ Advisory Board"
        url: "#advisory-board"
      - name: "/ Join us"
        url: "https://mlinpl-recruitment.paperform.co/"
        target: "_blank"
      - name: "/ Contact"
        url: "#contact"    


# Defaults for different pages
defaults:
  - scope:
      path: ""
    values:
      image: /images/mlinpl-conference-2025-event-banner.png


# Colors and styles settings
photo-border-width: 1px
color:
  main: "#E7322A"
  second: "#010101"
  default-text: "#010101"
  main-gradient: "#E7322A, #FF00FF"
  background: "#FFFFFF"
  person-photo-filter: "grayscale(75%)"
  person-photo-gradient: "linear-gradient(140deg, rgba(231,50,42,0) 25%,rgba(231,50,42,0.5) 100%)"


# Footer settings
footer: ML in PL Association


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    icon: linkedin
    url: https://www.linkedin.com/company/mlinpl
  - title: facebook
    icon: facebook
    url: https://www.facebook.com/MLinPL
  - title: twitter
    icon: x-twitter
    url: https://twitter.com/mlinpl
  - title: youtube
    icon: youtube
    url: https://www.youtube.com/channel/UCmXKn-Xeq1ZTAQBTwsYw4AA


# Build settings
theme: minima
plugins:
  - jekyll-seo-tag

markdown: kramdown
permalink: pretty

sass:
  style: compressed # possible values: nested expanded compact compressed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - drafts/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
  - googleb6957abd960a4507.html