years:
  - "2026"
default_year: "2026"
site_url: "https://conference.mlinpl.org"
root_copies:
  - source: "about-ml-in-pl-conference.html"
  - source: "privacy-policy.html"
  - source: "terms-of-participation.html"
  - source: "call-for-contributions.html"
  - source: "call-for-tutorials.html"
