#!/usr/bin/python
import os
import sys
import pandas as pd


CFC_BASE_CONFIG = {
    "sort_values": ["Id", "Time", "Room"],
    "fields": {
        "author-name": lambda row: row["Name and surname"].strip(),
        "title": lambda row: '"' + row["Title of your talk or poster"].strip() + '"',
        "author-title": lambda row: '"' + row["Affiliation"].strip() + '"',
        "abstract": lambda row: ">- \n    "
        + row["Abstract"].strip().replace("\n", "\n    "),
        "author-bio": lambda row: ">- \n    "
        + row["Biography"].strip().replace("\n", "\n    "),
        "co-authors": lambda row: parse_co_authors(row),
        "date": lambda row: row["Date"].strip(),
        "time": lambda row: row["Time"].strip(),
        "room": lambda row: row["Room"].strip().replace("Lecture Hall", "Hall"),
        "session": lambda row: row["Session"].strip(),
        "id": lambda row: int(row["Id"]),
        "author-image": lambda row: get_file(
            os.path.join(
                "images/optimized/cfc-600x600/",
                polish_to_ascii(
                    "_".join(s.lower() for s in row["Name and surname"].split(" "))
                )
                + ".webp",
            ),
            "images/empty.png",
        ),
    },
}
CFC_TALKS_CONFIG = {
    **CFC_BASE_CONFIG,
    "filter_columns": ["Accepted CfC Talk", "Confirmed"],
}
CFC_POSTERS_CONFIG = {
    **CFC_BASE_CONFIG,
    "filter_columns": ["Accepted Poster", "Confirmed"],
}
SRW_TALKS_CONFIG = {
    **CFC_BASE_CONFIG,
    "filter_columns": ["Accepted SRW Talk", "Confirmed"],
}


CONFIGS = {
    "conference-organizers": {
        "sort_values": [
            "Kolejność na WWW",
            "Nazwisko",
            "Pełna nazwa roli (autogenerated)",
        ],
        "fields": {
            "name": lambda row: row["Imię"].strip() + " " + row["Nazwisko"].strip(),
            "title": lambda row: row["Pełna nazwa roli (autogenerated)"].strip(),
            "linkedin": lambda row: row["LinkedIn"].strip(),
            "twitter": lambda row: row["Twitter"].strip(),
            "image": lambda row: get_file(
                os.path.join(
                    "images/optimized/organizers-300x300/",
                    polish_to_ascii(row["Imię"].strip())
                    + polish_to_ascii(row["Nazwisko"].strip())
                    + ".webp",
                ),
                "images/empty.png",
            ),
        },
    },
    "cfc_talks": CFC_TALKS_CONFIG,
    "cfc_posters": CFC_POSTERS_CONFIG,
    "srw_talks": SRW_TALKS_CONFIG,
}


def get_file(path, empty_path):
    if os.path.isfile(path):
        return path
    else:
        return empty_path


PL_TO_ASCII = {
    "ą": "a",
    "ć": "c",
    "ę": "e",
    "ł": "l",
    "ń": "n",
    "ó": "o",
    "ś": "s",
    "ź": "z",
    "ż": "z",
    "Ą": "A",
    "Ć": "C",
    "Ę": "E",
    "Ł": "L",
    "Ń": "N",
    "Ó": "O",
    "Ś": "S",
    "Ź": "Z",
    "Ż": "Z",
    ",": "",
}


def polish_to_ascii(text):
    for pl, ascii in PL_TO_ASCII.items():
        text = text.replace(pl, ascii)
    return text


def parse_co_authors(row):
    if "Co-authors" in row and row["Co-authors"].strip():
        return row["Co-authors"].strip()
    else:
        co_author_columns = [col for col in row.index if col.startswith("co-author")]
        co_authors = [row[col].strip() for col in co_author_columns if row[col].strip()]
        return ", ".join(co_authors)

def main(input_file, output_file, config):
    # Get config
    if config in CONFIGS:
        config = CONFIGS[config]
    else:
        raise Exception(
            f"Config {config} not found, available configs: {list(CONFIGS.keys())}"
        )

    sep = ","
    if input_file.endswith(".tsv"):
        sep = "\t"

    df = pd.read_csv(input_file, sep=sep, encoding="utf-8")
    if "filter_columns" in config:
        filter_columns = config["filter_columns"]
        filter_mask = None
        for filter_col in filter_columns:
            if filter_mask is None:
                filter_mask = (df[filter_col] == 1.0) | (df[filter_col] == "1")
            else:
                filter_mask *= (df[filter_col] == 1.0) | (df[filter_col] == "1")
        df = df[filter_mask]
        df = df.drop(columns=config["filter_columns"])
    print(df.info())

    df.fillna("", inplace=True)
    df.sort_values(by=config["sort_values"], inplace=True, ascending=True)

    with open(output_file, "w") as file:
        i = 0
        for id, row in df.iterrows():
            for j, (field, func) in enumerate(config["fields"].items()):
                if j == 0:
                    file.write("- ")
                else:
                    file.write("  ")
                file.write(f"{field}: {func(row)}\n")
                df.loc[id, field] = func(row)
            file.write("\n")
            i += 1
        file.close()
    print(f"Written {i} rows to {output_file}")


if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: csv_to_yaml.py <input_file> <output_file> <config>")
    else:
        main(sys.argv[1], sys.argv[2], sys.argv[3])
