import pandas as pd
import unidecode

# Example of a record in the output
# - name: "X X"
#   title: "X"
#   linkedin: "https://www.linkedin.com/in/X"
#   twitter: ""
#   image: "images/optimized/organizers-300x300/X.webp"

FILE = 'Organizatorzy ML in PL Conference 2025 Mastersheet - Sheet1.csv'

# Load the CSV file
df = pd.read_csv(FILE)

# Clean the column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
df.columns = [unidecode.unidecode(column) for column in df.columns]

# df = df.drop(columns=['numer_telefonu', 'nazwa_pliku_ze_zdjeciem', 'mail_firmowy', 'mail_prywatny/kontaktowy'])
# Drop the columns that are not needed
df = df[['imie', 'nazwisko', 'pelna_nazwa_roli_autogenerated', 'linkedin', 'twitter', 'kolejnosc_na_www']]

# Sort the data frame by the order on the website
df = df.sort_values(by=['kolejnosc_na_www', 'nazwisko'])

# Write the data to the YAML file
with open("organizers.yml", "w") as f:
    for i, row in df.iterrows():
        image_name = unidecode.unidecode(row['imie'] + row['nazwisko']).replace(' ', '')
        record = {
            'name': row['imie'].strip() + ' ' + row['nazwisko'].strip(),
            'title': row['pelna_nazwa_roli_autogenerated'],
            'linkedin': row.linkedin if pd.notna(row.linkedin) else '',
            'twitter': row.twitter if pd.notna(row.twitter) else '',
            'image': f'images/optimized/organizers-300x300/{image_name}.webp'
        }
        for i, (key, value) in enumerate(record.items()):
            if i == 0:
                f.write("- ")
            else:
                f.write("  ")
            f.write(f"{key}: \"{value}\"\n")
        f.write("\n")
